# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-paginate-multiple
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: fndomariano # jekyll-seo-tag > Owners twitter username
author: fndomariano # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Fernando Mariano # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/fndomariano
    - https://www.linkedin.com/in/fndomariano
    - https://github.com/fndomariano
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Sao_Paulo # Timezone for blog posts and alike

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Fernando Mariano" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "https://fndomariano.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "fernando.mar16@gmail.com"
disqus: "https-fndomariano-github-io" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-123045719-1'
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: br
  url: /
- title: en
  url: /en/
navigation_footer:
- title: Created by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/fndomariano
  LinkedIn: https://www.linkedin.com/in/fndomariano
  GitHub: https://github.com/fndomariano
  link: https://fndomariano.github.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: false
  linkedin: "#0073b1"

paginate_multiple:
  - paginate: 5
    paginate_path: '/pagina:num/'
    sub_dir: '/br'
  - paginate: 5
    paginate_path: '/en/page:num/'
    sub_dir: '/en'
