theme: jekyll-theme-cayman
title: Fernando Mariano
show_downloads: false
paginate: 5
paginate_path: /posts/:num/
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-seo-tag]
google_analytics: 'UA-123045719-1'